### ISSUE TITLE
Missing requirement for community.postgresql collection

### ISSUE THREAD

**Issue by doubletwist13** [mrlesmithjr/ansible-postgresql#18]
**Describe the bug**
When including this collection and the requirements as written, the `include_tasks: dbs.yml` fails with the following error:

```
{
  "reason": "couldn't resolve module/action 'postgresql_db'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/usr/share/ansible/roles/ansible-postgresql/tasks/dbs.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: dbs | Managing Databases\n  ^ here\n"
}
```

**To Reproduce**

With the following `requirements.yml`:
```
---
collections:
  - name: mrlesmithjr.netbox

roles:
  - src: https://github.com/mrlesmithjr/ansible-bootstrap-python.git
  - src: https://github.com/mrlesmithjr/ansible-postgresql
  - src: https://github.com/mrlesmithjr/ansible-redis

```

Result is the error above.

**Expected behavior**
Should successfully import the dbs.yml task

**Desktop (please complete the following information):**
 - AWX 21.5.0
- Custom Execution Environment based on `quay.io/ansible/ansible-runner:stable-2.12-latest` using the `requirements.yml` noted above.

**Additional context**
By adding `community.postgresql` to the list of required collections, the task succeeds as expected.

```
---
collections:
  - name: mrlesmithjr.netbox
  - name: community.postgresql

roles:
  - src: https://github.com/mrlesmithjr/ansible-bootstrap-python.git
  - src: https://github.com/mrlesmithjr/ansible-postgresql
  - src: https://github.com/mrlesmithjr/ansible-redis
```
