### ISSUE TITLE
Trying to understand role

### ISSUE THREAD

**Issue by till** [mrlesmithjr/ansible-postgresql#9]
It seems like one cannot have replication(`.yml`), without doing config(`.yml`), as the replication setup relies on vars set in config (and fails otherwise).

But I was wondering if you could extend your example for replication.

**Comment by till** [comment]
With 9.6 (your current default) this was necessary:

```
    - name: Create config directory
      file:
        path: /etc/postgresql/{{ postgresql_version }}/main
        state: directory
```

I would also do something like:

```
postgresql_replication:
          interface: "{{ ansible_default_ipv4.interface }}"
```
